### ISSUE TITLE
Criar o Alfabeto em Pixel art

### ISSUE THREAD

**Issue by EricFerreiraFR** [EricFerreiraFR/Zona_de_Contagio#6]
Criar todas as letras do alfabeto

**Comment by EricFerreiraFR** [comment]
Adicionado todas as letras do alfabeto


![Image](https://github.com/EricFerreiraFR/Zona_de_Contagio/assets/50562020/bd9d5e06-538e-4a6d-97dd-aceacb6313df)

**Comment by MKNakao** [comment]
ok
